### PR TITLE
Update project 2 markdown file

### PR DESCRIPTION
**Pull request by changsiyao**
First draft of project 2 description.
Please give advice.

@MengfeiJiang @pttzty

### CODE REVIEW

**Comment by changsiyao** [comment]
#7

**Comment by changsiyao** [comment]
Update pull request for CI and travis updates to pass checks.
Now passing checks and coverage remains stable.

**Comment by jarrodmillman** [comment]
If you can arrive a few minutes early to class on Monday, I will help you merge this.  I will want you to rebase it off master first and I can walk you through the process then.

**Comment by changsiyao** [comment]
@jarrodmillman I think I have rebased and force pushed my file. Can you check if I have done the right thing?
Thanks!

**Pull request merged**
