### PR TITLE
MRG: add classification setup

### PR DESCRIPTION
**Pull request by changsiyao**

### CODE REVIEW

**Comment by changsiyao** [comment]
@jarrodmillman Can you check if my setup for the classification project is fine? And if it is, would you merge it for us? Thanks!

**Comment by changsiyao** [comment]
@MengfeiJiang Can you also take a look and see if I can change this to MRG? Thanks

**Comment by MengfeiJiang** [comment]
The structure looks fine to me. @changsiyao

**Comment by pttzty** [comment]
Good. We will pull from the new branch then.

**Comment by changsiyao** [comment]
@jarrodmillman Could you please take a look and merge if it is ok? Thanks!

**Pull request merged**
