### PR TITLE
WIP: Revise TESTFLOW.rst

### PR DESCRIPTION
**Pull request by boyinggong**
Change all test documents about numpy test to pytest.
#64

### CODE REVIEW

**Comment by shamindras** [comment]
@boyinggong - what is the status on this. I see the reference to #78 but that is already closed? Has this been reviewed internally?

Do you need us to take a final review before MRGing?

**Comment by boyinggong** [comment]
@shamindras Sorry I linked to the wrong issue, I've corrected this

**Comment by shamindras** [comment]
@boyinggong - no problem. Are you still reviewing/ updating this internally as a team?

I believe all of the numpy testing references can be completely removed. Only need to keep `pytest` references and examples as this is the only one we will be using.

**Comment by boyinggong** [comment]
@shamindras Yes, we are still editing the pytest part. Can I remove the numpy test section as well as the  [example file](https://github.com/berkeley-stat222/mousestyles/blob/master/mousestyles/tests/test_data_utils.py) for numpy? All examples for testing will be in the TESTFLOW.rst file. Maybe I can link to siyao's code #57 for supplement material after merging her pull request.

**Comment by shamindras** [comment]
@boyinggong - thanks. For your questions:

> Can I remove the numpy test section as well as the example file for numpy?

Yes - please. As long as the numpy examples are replaced with suitable `pytest` equivalent tests.

> All examples for testing will be in the TESTFLOW.rst file. Maybe I can link to siyao's code #57 for supplement material after merging her pull request.

I think it is best to incorporate the examples directly in the document i.e. pasting and editing them as suitable rather than linking to a dynamic document which changes frequently. In review you may wish to compare and decide whether linking is better/ easier for the reader.

**Comment by peterasujan** [comment]
Hey @boyinggong, before we merge this, can you rebase it off master? See [here](https://github.com/berkeley-stat222/mousestyles/blob/master/CONTRIBUTING.rst#divergence-between-upstream-master-and-your-feature-branch) for details.

**Comment by jarrodmillman** [comment]
It looks like this pull request deletes some of the existing tests for data_utils.

**Comment by jarrodmillman** [comment]
This is also a pull request from boyinggong:master which means it can't be rebased.  This needs to be started over on a branch and redone.  I can show you how to do that in class.

**Comment by boyinggong** [comment]
@jarrodmillman Yes, I deleted some of the existing test. Because they are not based on pytest. Also, these tests are numpy testing example just for illustration and I think they can not be passed.

**Comment by boyinggong** [comment]
@jarrodmillman So we're always supposed to open pull request from our branch for specific issues rather than from master? Maybe I can discuss this with you tmr.

**Pull request closed without merging**
