### PR TITLE
WIP: Path Diversity Plotting Function

### PR DESCRIPTION
**Pull request by alannaiverson**
Referencing issue #122 

These two functions allow for box plots and histograms to be created based on the output of our feature functions.

Please comment and review if you need a pull request review!

@aksam-ahmad @jJasonWang @sicihuang @togawa28 @jcpalumbo3

### CODE REVIEW

**Comment by jJasonWang** [comment]
I tried the function for the first strain, first mouse across 12 days. One suggestion: we probably need an argument to adjust the figure size. This picture is the plot:
p1

Maybe two arguments and add the `plt.figure(figsie=(arg1, arg2))`?

**Comment by jJasonWang** [comment]
Also, because we might use the function to compare the strain, mouse, and day at the same time, we probably need a more systematic way to create the plots as well as the labels.

I have two ideas (for boxplot):
1. Make a big plot which x-axis would be one variable such as day. Then for each day, we will have different colors boxplots which represent another variable like mouse. So for each day, there might be a red boxplot for mouse1, blue boxplot for mouse2, and green boxplot for mouse3. This method can only show two variables information. It will be something like:
p2
2. Make a facet or panel plot. It might be complicated. Each axis can represent one variable. Within each subplot, we can show the variation for each day. It will be something like:
p1
I created the example by ggplot2 in R. I am not sure how hard it will be to implement in Python. I'm definitely willing to help. We can have a detailed discussion tomorrow.

**Comment by alannaiverson** [comment]
Good point @jJasonWang. I think this function is mainly for smaller plots to be used in our less formal analysis since larger plots will be highly specialized.

Also, the coverage failed because this is a plotting function that can't be tested. It will be proven to output correct plots in our write up when it is called there.

**Comment by jJasonWang** [comment]
Yeah, then you can change it to MRG once you finish adding the figure size.

**Comment by jarrodmillman** [comment]
@alannaiverson Would you mind adding one or two example plotting scripts (I suspect they will be 3-4 liners since you've already written the plotting function) here
  https://github.com/berkeley-stat222/mousestyles/tree/master/doc/source/report/plots
and then using the plot directive include the plots in your report
  https://github.com/berkeley-stat222/mousestyles/blob/master/doc/source/report/path.rst

You can just put a placeholder in for now, if you aren't ready to produce final plots.  I would like to point out what you did so that others can see how it works (which is why I would like you to add the example scripts to the report).

If you can get to this soon, I will merge your pull request next.  I've merged a few other pull requests recently, so make sure you rebase as well.

**Comment by alannaiverson** [comment]
@jarrodmillman I can get to this tonight, I actually found a little bug in the plotting function so I'll need to fix that first.

I know the existing path.rst has an example plot in it, but it doesn't appear to be rendering. It is the heat map example we worked on, but it is not appearing in the HTML or markdown versions. Looking at the raw code, it shows that the correct script is being referenced but no plot is showing up. I'm specifically looking at this raw, though I don't see the plot being generated: https://raw.githubusercontent.com/berkeley-stat222/mousestyles/master/doc/source/report/path.rst

Any ideas why? If that isn't the correct way to reference the plotting script, what is?

**Comment by jarrodmillman** [comment]
@alannaiverson To render the plots, you need to do this from the top level of the working tree:

```
$ cd mousestyles/doc/source
$ make html
```
To build the PDF use
```
$ make latexpdf
```

I update the website using
```
$ make github
```

You can see the rendered website here:
http://berkeley-stat222.github.io/mousestyles/report/path.html
```

**Comment by alannaiverson** [comment]
@jarrodmillman Ok I tried that exactly but when I run the html and pdf commands, the plot does not appear in the _build files but I'm not sure why. It appears in the website but neither of the other places for me after following those exact instructions. I can add another script and change the .rst to see if that works now

**Comment by alannaiverson** [comment]
@jarrodmillman Great, why did me changing one line in my function cause 8 files to be "edited?" I rebased prior to pushing... I changed the back to WIP since I don't know why 8 files were changed and so many commits that aren't mine were added to this pull request

**Comment by jarrodmillman** [comment]
I am not sure what you did, but it doesn't look like you rebased your branch on the upstream master.  To make things simpler, I decided to just handle the pull request myself.  I added your fork as a remote, fetched your branch to my local repository, branched off my local master which I keep in sync with the upstream master, cherry-picked your commits, and made a new pull request.

```
$ git remote add alanna git@github.com:alannaiverson/mousestyles.git
$ git fetch alanna path_plot
$ git checkout master
$ git pull upstream master
$ git checkout -b alannaiverson-path_plot
$ git cherry-pick  49e09f5  fdb95fd  e1ba5d3  82eae92 0abfed4
$ git push origin alannaiverson-path_plot
```

Here is the new pull request: #162

**Pull request closed without merging**
