### PR TITLE
MRG: add data loader that load features of each 2-hr bin

### PR DESCRIPTION
**Pull request by changsiyao**
Please see #141

### CODE REVIEW

**Comment by changsiyao** [comment]
@MengfeiJiang @pttzty Please look through and give suggestions. Right now, it returns only the features we input. I can also make it return all 9*11 features. Let me know what you prefer.

**Comment by pttzty** [comment]
I think the function enables the selection of the subset of features used in our clustering algorithms, but it would be better if we can specify that the 11 levels of each feature are labeled as, for example: Food 0, Food 2, ..., Food 20, otherwise it's pretty confusing because users might think there are 20 levels for each feature.

**Comment by changsiyao** [comment]
@ye-zhi @lichenzhi @lizhua Please review this function, this function is for the classification.

**Comment by lizhua** [comment]
What if we just want one feature as input, do we still have to put it in a list? Maybe we should check input. It's really easy to mess up the input if we only need one feature.

**Comment by changsiyao** [comment]
@lizhua OK, I added a few lines to check and raise error. Please review again.

**Comment by lizhua** [comment]
Looks Fine! I think you can change it to MRG! Thank you

**Comment by changsiyao** [comment]
@jarrodmillman Would you merge this new data loading function please? We need this for classification. Thank you!

**Pull request merged**
