### PR TITLE
WIP: modified testflow.md

### PR DESCRIPTION
**Pull request by lynnzhao92**
changed the details in TESTFLOW.md

### CODE REVIEW

**Comment by dylandaniels** [comment]
Hey @lynnzhao, running the tests isn't as simple as just typing "make test." You also need to make sure the package has been built and installed. Can you add the specific commands for this to the instructions?

**Comment by jarrodmillman** [comment]
An alternative, which could be an and/or as you (plural) decide makes sense, is to have make run some dependent commands for the `test` target.

**Comment by dylandaniels** [comment]
@lynnzhao @jarrodmillman -- @peterasujan is working a fix now. He's going to have make test call another target which builds & installs first.

**Comment by peterasujan** [comment]
This was implemented in #54, so I think just referring to `make test` is sufficient.
@lynnzhao it looks like the build is failing because there are lingering style errors. @jarrodmillman fixed these on master in #49, so if you rebase, the build should pass. Let me know if you'd like some guidance on how to do that.

**Comment by shamindras** [comment]
@lynnzhao - is it possible for you to rebase this and fix the style errors per @peterasujan's suggestion?

Once the Travis build is passing i.e. green tick mark, you can change the status to 'MRG' and tag Dylan, Peter or myself and we can merge this.

**Pull request closed without merging**
