### PR TITLE
MRG: Revision of Project 2: Path model

### PR DESCRIPTION
**Pull request by togawa28**
Revised the overview of the project 2 which is about the path diversity. @jarrodmillman ,@peterasujan, @shamindras please review the changes.

### CODE REVIEW

**Comment by shamindras** [comment]
@togawa28 - is this ready to MRG? If so could you please change the status?

**Comment by togawa28** [comment]
As we are not really sure what we can suggest in the section of testing outline, we are just worrying that some of us would comment and revise the contents in this section. If the reviewers think there's no problem, I'm totally happy to change status to MRG.

**Comment by shamindras** [comment]
@togawa28 - perhaps it is a good idea to present tomorrow and get feedback from @jarrodmillman / class to edit that section and then change to MRG. Will leave not MRG at this point

**Comment by togawa28** [comment]
@shamindras - Our group talked in a class that since all of us were working on the separate parts and each of us already reviewed other's parts, it is we think ready to merge. I'll change the status to MRG, but feel free to point out any contents that you think need to be modified before merging.

**Comment by shamindras** [comment]
@togawa28 - that is fine. All sections are now completed and we can MRG

**Pull request merged**
