### PR TITLE
MRG: BUG: Fix incorrect data loading due to filename inconsistency.

### PR DESCRIPTION
**Pull request by peterasujan**
See https://github.com/berkeley-stat222/mousestyles/issues/107#issuecomment-217292169 for discussion.
@jarrodmillman this probably should be merged quickly, as it may impact several other groups' work. It may also warrant an announcement on Piazza.

### CODE REVIEW

**Comment by dylandaniels** [comment]
seconding this. please mrg asap.

**Comment by jarrodmillman** [comment]
@peterasujan , I merged a few PR recently, please rebase and I will merge.

**Comment by peterasujan** [comment]
@jarrodmillman done. Thanks for the heads-up!

**Comment by jarrodmillman** [comment]
@peterasujan Travis is busy, so I am going to just merge this since it looks good and passed before.  I will keep an eye on it, in case this causes problems.

**Pull request merged**
