### PR TITLE
WIP: update classification.md

### PR DESCRIPTION
**Pull request by doutib**

### CODE REVIEW

**Comment by shamindras** [comment]
@doutib - what is the difference between this and PR #55?

They look like MRG requests for the same file

**Comment by jarrodmillman** [comment]
This appears to be a test push.  Should I go ahead and close (without merging) it?

**Comment by doutib** [comment]
You can merge this one. I have deleted the previous one, since this one addresses the issues mentioned earlier.

**Comment by jarrodmillman** [comment]
@doutib , I think you may want to just close this pull request.  It hardly adds any new content nor improves the existing content.  It also adds a number of useless commits to our project history.

Why don't you close this pull request and start again.  This way we will have a clean history.  Also try to improve the text in a substantial and thoughtful way before asking for your work to be merged.

**Pull request closed without merging**
