### PR TITLE
MRG: change naming convention for feature branch

### PR DESCRIPTION
**Pull request by jJasonWang**
See #14 ( feature branch naming convention).

Please review @aksam-ahmad, @togawa28.

### CODE REVIEW

**Comment by aksam-ahmad** [comment]
Do we want to keep the **issue#** in the naming convention? If not, I think it'd be a good idea to at least mention that it is possible to reference a specific issue in naming a branch. Thoughts?

**Comment by jJasonWang** [comment]
I removed it because the person who creates the pull request will mention the **issue#** in the pull request. I think the purpose of the naming convention for the feature is that it will make people quickly know what this branch is for, right? 
Or we can make it like _feature_-issue#. For example, contributing-issue#14.

**Comment by aksam-ahmad** [comment]
Fair point. We can leave as is. @shamindras could you please review and chime in if you feel otherwise?

**Comment by shamindras** [comment]
@aksam-ahmad @jJasonWang - we should make it `feature-desc-issue#` for now. In the CONTRIBUTING.rst we can change to this.

@aksam-ahmad if you review this change and accept it and change to MRG. I can add it in

**Comment by shamindras** [comment]
Changes to the CONTRIBUTING file are as agreed with group.

Merging now.

**Pull request merged**
