### PR TITLE
MRG: Adding visualization folder setup

### PR DESCRIPTION
**Pull request by changsiyao**
@jJasonWang @alannaiverson 
Hey, I created the visualization folder, help me check if the setup is correct. We probably won't be testing these plotting functions, that's why I didn't create a test folder.
Let me know what you guys think.

### CODE REVIEW

**Comment by jJasonWang** [comment]
The setup looks good to me. One little thing for tests: should we test the input of the visualization function? (if there are some parameters the user can adjust) Well, it is too hard to say now. What do you think @alannaiverson?

**Comment by alannaiverson** [comment]
My functions validate input and raise errors if the inputs aren't what is expected, so I don't think we need any other testing or a test folder. But we can talk tomorrow to confirm @jJasonWang!

**Comment by changsiyao** [comment]
Well, I guess we can check if functions are returning appropriate errors, but that's not exactly testing if the functions are doing what we want them to do, since the these functions are just showing a graph, and not even returning anything. But, we can talk about that in class tmr. Thanks! @jJasonWang @alannaiverson

**Comment by CenzhuoYao** [comment]
This looks good. I think you can change it merge. @changsiyao

**Pull request merged**
