### PR TITLE
WIP: Update Project 1 (Consistency)

### PR DESCRIPTION
**Pull request by CenzhuoYao**

### CODE REVIEW

**Comment by dylandaniels** [comment]
looks good!

**Comment by peterasujan** [comment]
@CenzhuoYao is this ready to merge? If so, please change the status to MRG and I'll pull it in.

**Comment by jarrodmillman** [comment]
This is pretty much an empty commit.  It just changed the headings of some paragraphs.

I don't know if there is a plan for someone else to update the content of the summary.  If not, I would recommend working on this pull request more before merging.

**Comment by shamindras** [comment]
@CenzhuoYao - this doesn't look updated. In our revision we have made many changes to this file. Could I please close this issue without MRG'ing?

**Comment by CenzhuoYao** [comment]
@shamindras Please just close it. I thought we should make the project description consistent, but it seems that the group who reviews our project should do it.

**Pull request closed without merging**
