### PR TITLE
WIP: documentation for setup SSH key

### PR DESCRIPTION
**Pull request by jJasonWang**
See #14.

Please review @aksam-ahmad, @togawa28.

### CODE REVIEW

**Comment by peterasujan** [comment]
@jJasonWang thanks for adding this. Only thing you might want to add is a disclaimer that this probably won't work on Windows. Other than that, if you're ready to merge, you should change the status of the PR to MRG.

**Comment by shamindras** [comment]
@peterasujan - re:

> @jJasonWang thanks for adding this. Only thing you might want to add is a disclaimer that this probably won't work on Windows. Other than that, if you're ready to merge, you should change the status of the PR to MRG.

Github has [great documentation](https://help.github.com/articles/generating-an-ssh-key/#platform-mac) for SSH key setup. Up the top of each instruction page there is a _toggle_ for Windows/ Unix instructions. Users should be able to follow either right?

**Comment by peterasujan** [comment]
Good find. I think we're good to go.

**Comment by shamindras** [comment]
@peterasujan Great - I'll merge now

**Pull request merged**
